version: "3"

services:
    nginx1:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html

    nginx2:
        image: nginx
        ports:
            - 8001:80
        volumes:
            - ./src:/usr/share/nginx/html
#            - ./nginx.conf:/etc/nginx/conf.d/default.conf
